package com.rest.calc;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class CalcHtml {

	@RequestMapping(value = "/")
	public String name() {
		return "<!DOCTYPE html>\n"
				+ "<html>\n"
				+ "<head>\n"
				+ "<meta charset=\"UTF-8\">\n"
				+ "    <title>Calculator</title>\n"
				+ "    <style>\n"
				+ "        body {\n"
				+ "            font-family: Arial, sans-serif;\n"
				+ "            display: flex;\n"
				+ "            justify-content: center;\n"
				+ "            align-items: center;\n"
				+ "        }\n"
				+ "        .calculator {\n"
				+ "            padding: 20px;\n"
				+ "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
				+ "        }\n"
				+ "        .calculator input {\n"
				+ "            width: 96%;\n"
				+ "            padding: 10px;\n"
				+ "            margin-bottom: 10px;\n"
				+ "            border: 1px solid #ccc;\n"
				+ "        }\n"
				+ "        .calculator button {\n"
				+ "            width: 100%;\n"
				+ "            padding: 10px;\n"
				+ "            margin-bottom: 5px;\n"
				+ "            border: none;\n"
				+ "            border-radius: 9px;\n"
				+ "            background-color: #007bff;\n"
				+ "            color: #fff;\n"
				+ "            font-size: 16px;\n"
				+ "        }\n"
				+ "        .calculator button:hover {\n"
				+ "            background-color: #0056b3;\n"
				+ "        }\n"
				+ "        .result {\n"
				+ "            margin-top: 10px;\n"
				+ "            margin-bottom: 10px;\n"
				+ "            width: 100%;\n"
				+ "            height: 30px;\n"
				+ "            font-size: 18px;\n"
				+ "            border:2px solid black ;\n"
				+ "        }\n"
				+ "    </style>\n"
				+ "</head>\n"
				+ "<body>\n"
				+ "    <div class=\"calculator\">\n"
				+ "        <h1>Simple Calculator</h1>\n"
				+ "        <div class=\"result\" id=\"result\"></div>\n"
				+ "        <input type=\"number\" id=\"num1\" placeholder=\"Enter first number\" />\n"
				+ "        <input type=\"number\" id=\"num2\" placeholder=\"Enter second number\" />\n"
				+ "        <button onclick=\"calculate('add')\">Add</button>\n"
				+ "        <button onclick=\"calculate('subtract')\">Subtract</button>\n"
				+ "    </div>\n"
				+ "    <script>\n"
				+ "        async function calculate(operation) {\n"
				+ "            const num1 = document.getElementById('num1').value;\n"
				+ "            const num2 = document.getElementById('num2').value;\n"
				+ "\n"
				+ "            if (num1 === '' || num2 === '') {\n"
				+ "                document.getElementById('result').innerText = 'Please enter both numbers.';\n"
				+ "                return;\n"
				+ "            }\n"
				+ "\n"
				+ "            try {\n"
				+ "                const response = await fetch(`http://localhost:8080/${operation}?num1=${num1}&num2=${num2}`);\n"
				+ "                const resultText = await response.text();\n"
				+ "                document.getElementById('result').innerText = resultText;\n"
				+ "            } catch (error) {\n"
				+ "                document.getElementById('result').innerText = 'Error: Unable to perform the operation.';\n"
				+ "            }\n"
				+ "        }\n"
				+ "    </script>\n"
				+ "</body>\n"
				+ "</html>";
	}
	
	
}
